# Postgres settings
POSTGRES_HOST=127.0.0.1
POSTGRES_PORT=5432
POSTGRES_USER=codesensei
POSTGRES_PASSWORD=averysecurepassword
POSTGRES_DB=codesensei

# Redis settings
REDIS_HOST=127.0.0.1
REDIS_PORT=
REDIS_PASSWORD=
RESQUE_NAMESPACE=

# Submissions settings
# MEMORY_LIMIT=
# MAX_MEMORY_LIMIT=
# CPU_TIME_LIMIT=
# MAX_CPU_TIME_LIMIT=
# CPU_EXTRA_TIME=
# MAX_CPU_EXTRA_TIME=
# WALL_TIME_LIMIT=
# MAX_WALL_TIME_LIMIT=
# STACK_LIMIT=
# MAX_STACK_LIMIT=
# ITERATIONS=
# MAX_ITERATIONS=
# MAX_PROCESSES_AND_OR_THREAD=
# MAX_MAX_PROCESSES_AND_OR_THREADS=
# REDIRECT_STDERR_TO_STDOUT=
# ALLOW_NETWORK=

# ENABLE_CALLBACK=
# ENABLE_COMPILER_OPTIONS=
# ENABLE_COMMAND_LINE_ARGUMENTS=
# CALLBACK_TIMEOUT=
# CALLBACK_MAX_RETRIES=
# SUBMISSION_CACHE_DURATION=

# Worker settings
# POLL_INTERVAL=
# WORKER_COUNT=
# MAX_QUEUE_SIZE=

# Server settings
# ALLOW_ORIGIN=
# DISALLOW_ORIGIN=
# ALLOW_IP=
# DISALLOW_IP=
SERVER_PORT=3000
